### ISSUE TITLE
adapt header section and logo in the new site

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/sarit-pm#2]
the new site was generated with TEI PM app wizard - the project needs to be updated with the Sarit logo and adaption of header to new site.

**Comment by plutonik-a** [comment]
I chose not to use the original logo, because the quality was really poor and couldn't be further processed, plus, so far no source files are available.

I decided to process the logo as a placeholder in hope to get the source files later and adapted the Bootstrap "navbar-inverse" layout that you use for TEI PM apps by default: 
Dark header with white text color.
As primary color, I chose the grayish-blue color from the original Sarit image.

Also, I split the long headline into brand name and slogan to get the focus on the product name and clear-up the layout.

**Comment by plutonik-a** [comment]
Related: https://github.com/eXistSolutions/sarit-pm/issues/8

**Comment by plutonik-a** [comment]
Fixed with 
https://github.com/eXistSolutions/sarit-pm/commit/c3e269e7ca2de8015015573838d6ca6f96ab6132
https://github.com/eXistSolutions/sarit-pm/commit/8995f4b3ccf3774deddfd1bbdefe4f631c714c4f
https://github.com/eXistSolutions/sarit-pm/commit/ef4bab375bccdfa3740c5ae9bf59369de665a06a
https://github.com/eXistSolutions/sarit-pm/commit/13cc6bcd4acb053230e8b966fa4f18865651b8ea

**Comment by plutonik-a** [comment]
If no source files can be delivered by the customer, we could make an offer to provide the logo-design ourselves.
